### ISSUE TITLE
View Heart Rate Time Series in historical dashboard

### ISSUE THREAD

**Issue by alyandon** [jlai/fitness-dashboard#37]
I apologize in advance if this is the wrong place to ask about potential new features but I am a refugee from the fitbit.com official dashboard since they shut it down.

API call is here:  https://dev.fitbit.com/build/reference/web-api/heartrate-timeseries/

Would it be possible for you to add support for something like that to the historical dashboard?

**Comment by jlai** [comment]
Yep, this is the place.

That API call is for Resting Heart Rate (only calculated during sleep) and heart rate zones (time spent in different zones, but not the actual heart rate), which there's already graphs for.

There's another API for intraday heart rate data, which gives the detailed (minute-level) heart rate for a 24-hour period.

The intraday data is much more fine-grained than the other historical graphs so I'm figuring out how to incorporate it into there. For now, the other intraday graphs (steps, calories, distance) are available in the details tab when you click on the dashboard tile, since it's easier to put custom charts in there vs the historical graphs which try to handle all different graph types in one place.

It might make sense to add a heart rate tile to make it easily accessible for the current day.

**Comment by jlai** [comment]
I've added a heart rate tile to the dashboard. Edit Grid -> Add Tile -> Heart Rate. Click on it for the intraday graph.

**Comment by alyandon** [comment]
Very nice!  Thanks for that.
