### ISSUE TITLE
Email for low battery status

### ISSUE THREAD

**Issue by jetpowercom** [jlai/fitness-dashboard#63]
Wow, I join others here with great appreciation for building and sharing this!  Thank you (and google should thank you for taking some frustration out of folks whose exercise data are now part of their user base)!  

Here's my request:

The Fitbit web site bundled battery level reports with user email address and mail to send us emails advising when the Fitbit battery was low.  Might that be possible to implement with the Fitness Dashboard?

TIA for info.

**Comment by jlai** [comment]
Because this website doesn't have a server backend and doesn't access or monitor your data while your browser is closed, we don't have a way to send battery alerts.

I haven't tried but maybe Fitbit still sends battery alerts? I still get the weekly stats email. The setting is still visible in https://www.fitbit.com/settings/notifications

You can also keep an eye on your battery status from Fitness Dashboard via Edit Grid -> Add tile -> Battery & Sync time

**Comment by jetpowercom** [comment]
Thanks, I'll review notifications.  It may be possible that google reset a few things when closing the web portal.
